# C compiler and flags
CC=gcc-7
CFLAGS=-std=c99 -g

# C++ compiler and flags
CXX=g++-7
CXXFLAGS=-std=c++14 -g

# CUDA compiler and flags
NVCC=nvcc
#NVCCFLAGS=-O3 -std=c++11
NVCCFLAGS=-O3 -std=c99

# Optimization flags
OPTFLAGS=-O3 -march=native -fopenmp -ffast-math
CFLAGS+=$(OPTFLAGS)
CXXFLAGS+=$(OPTFLAGS)

# Python
PYTHON=python

# Lua front-end
LUA_CFLAGS=`pkg-config lua --cflags`
LUA_LIBS=`pkg-config lua --libs`

# Other necessary libraries
LIBS=-lm